/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as FileSlugRouteImport } from './routes/file.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const FileSlugRoute = FileSlugRouteImport.update({
  id: '/file/$slug',
  path: '/file/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/saved': typeof SavedRoute
  '/file/$slug': typeof FileSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/saved': typeof SavedRoute
  '/file/$slug': typeof FileSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/saved': typeof SavedRoute
  '/file/$slug': typeof FileSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/research' | '/saved' | '/file/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/research' | '/saved' | '/file/$slug'
  id: '__root__' | '/' | '/research' | '/saved' | '/file/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchRoute: typeof ResearchRoute
  SavedRoute: typeof SavedRoute
  FileSlugRoute: typeof FileSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$slug': {
      id: '/file/$slug'
      path: '/file/$slug'
      fullPath: '/file/$slug'
      preLoaderRoute: typeof FileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchRoute: ResearchRoute,
  SavedRoute: SavedRoute,
  FileSlugRoute: FileSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
